import React from "react";
import Typography from "@material-ui/core/Typography";
import List from "@material-ui/core/List";
import ListItemText from "@material-ui/core/ListItemText";
import casinoDatabase from "../casinoDatabase.png";

const SQL1 = () => (
  <div>
    <Typography variant="h6" component="h2" gutterBottom>
      {
        "Use these sentences to draw a schema of a database you would create to store these information."
      }
    </Typography>
    <List component="nav" aria-label="Secondary mailbox folders">
      <ListItemText primary="You are working in a casino." />
      <ListItemText primary="A casino has games." />
      <ListItemText primary="Each game has a unique type." />
      <ListItemText primary="Each game has one or more countries where players are allowed to bet from." />
      <ListItemText primary="A player may or may not have a favorite game." />
    </List>
    <Typography variant="h6" component="h2" gutterBottom>
      {
        "Send the image of the schema and also the sql to create the database and tables."
      }
    </Typography>
    <Typography variant="h6" component="h2" gutterBottom>
      {
        "Below is the picture representing my proposed solution to the database required."
      }
    </Typography>
    <img src={casinoDatabase} className="" alt="logo" />
    <Typography variant="h6" component="h2" gutterBottom>
      {"Below is the SQL Code used to create the database model."}
    </Typography>
    <Typography
      variant="h6"
      href={"https://yobetit-test.s3-sa-east-1.amazonaws.com/casinoScript.sql"}
    >
      {"You can download the sql file to download directly from "}
      <a
        className="App-link"
        href="https://yobetit-test.s3-sa-east-1.amazonaws.com/casinoScript.sql"
        target="_blank"
        rel="noopener noreferrer"
      >
        this link
      </a>
    </Typography>
    <text>
      {"-- MySQL Script generated by MySQL Workbench"}
      <br />
      {"-- Sun 30 Jun 2019 02:04:19 PM -03"}
      <br />
      {"-- Model: New Model    Version: 1.0"}
      <br />
      {"-- MySQL Workbench Forward Engineering"}
      <br />
      {"SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;"}
      <br />
      {
        "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;"
      }
      <br />
      {
        "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';"
      }
      <br />
      <br />
      {"-- -----------------------------------------------------"}
      <br />
      {"-- Schema mydb"}
      <br />
      {"-- -----------------------------------------------------"}
      <br />
      {"-- -----------------------------------------------------"}
      <br />
      {"-- Schema mydb"}
      <br />
      {"-- -----------------------------------------------------"}
      <br />
      {"CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;"}
      <br />
      {"USE `mydb` ;"}
      <br />
      {"----------------------------------------------------"}
      <br />
      {"-- Table `mydb`.`Casino`"}
      <br />
      {" -----------------------------------------------------"}
      <br />
      {"CREATE TABLE IF NOT EXISTS `mydb`.`Casino` ("}
      <br />
      {"  `idCasino` INT NOT NULL,"}
      <br />
      {"  `Name` VARCHAR(45) NOT NULL,"}
      <br />
      {"  PRIMARY KEY (`idCasino`))"}
      <br />
      {"ENGINE = CSV"}
      <br />
      {"DEFAULT CHARACTER SET = utf8"}
      <br />
      {"COMMENT = 'Tabela do Casino';"}
      <br />
      <br />
      {" -----------------------------------------------------"}
      <br />
      {" Table `mydb`.`Game`"}
      <br />
      {" -----------------------------------------------------"}
      <br />
      {"CREATE TABLE IF NOT EXISTS `mydb`.`Game` ("}
      <br />
      {"  `idGame` INT NOT NULL,"}
      <br />
      {"  `Name` VARCHAR(45) NOT NULL,"}
      <br />
      {"  `Casino_idCasino` INT NOT NULL,"}
      <br />
      {"  `Type` ENUM('CARD', 'LUCKY', 'PINBALL', 'SLOT') NOT NULL,"}
      <br />
      {"  PRIMARY KEY (`idGame`),"}
      <br />
      {"  INDEX `fk_Game_Casino_idx` (`Casino_idCasino` ASC),"}
      <br />
      {"  CONSTRAINT `fk_Game_Casino`"}
      <br />
      {"    FOREIGN KEY (`Casino_idCasino`)"}
      <br />
      {"    REFERENCES `mydb`.`Casino` (`idCasino`)"}
      <br />
      {"    ON DELETE NO ACTION"}
      <br />
      {"    ON UPDATE NO ACTION)"}
      <br />
      {"ENGINE = InnoDB"}
      <br />
      {"DEFAULT CHARACTER SET = utf8;"}
      <br /> <br />
      {" -----------------------------------------------------"}
      <br />
      {" Table `mydb`.`Country`"}
      <br />
      {" -----------------------------------------------------"}
      <br />
      {"CREATE TABLE IF NOT EXISTS `mydb`.`Country` ("}
      <br />
      {"  `idCountry` INT NOT NULL,"}
      <br />
      {"  `Name` VARCHAR(45) NULL,"}
      <br />
      {"  PRIMARY KEY (`idCountry`))"}
      <br />
      {"ENGINE = InnoDB;"}
      <br /> <br />
      {" -----------------------------------------------------"}
      <br />
      {" Table `mydb`.`AllowedListGameCountry`"}
      <br />
      {" -----------------------------------------------------"}
      <br />
      {"CREATE TABLE IF NOT EXISTS `mydb`.`AllowedListGameCountry` ("}
      <br />
      {"  `Game_idGame` INT NOT NULL,"}
      <br />
      {"  `Country_idCountry` INT NOT NULL,"}
      <br />
      {"  PRIMARY KEY (`Game_idGame`, `Country_idCountry`),"}
      <br />
      {"  INDEX `fk_Game_has_Country_Country1_idx` (`Country_idCountry` ASC),"}
      <br />
      {"  INDEX `fk_Game_has_Country_Game1_idx` (`Game_idGame` ASC),"}
      <br />
      {"  CONSTRAINT `fk_Game_has_Country_Game1`"}
      <br />
      {"    FOREIGN KEY (`Game_idGame`)"}
      <br />
      {"    REFERENCES `mydb`.`Game` (`idGame`)"}
      <br />
      {"    ON DELETE NO ACTION"}
      <br />
      {"    ON UPDATE NO ACTION,"}
      <br />
      {"  CONSTRAINT `fk_Game_has_Country_Country1`"}
      <br />
      {"    FOREIGN KEY (`Country_idCountry`)"}
      <br />
      {"    REFERENCES `mydb`.`Country` (`idCountry`)"}
      <br />
      {"    ON DELETE NO ACTION"}
      <br />
      {"    ON UPDATE NO ACTION)"}
      <br />
      {"ENGINE = InnoDB"}
      <br />
      {"DEFAULT CHARACTER SET = utf8;"}
      <br />
      <br />
      {" -----------------------------------------------------"}
      <br />
      {" Table `mydb`.`Player`"}
      <br />
      {" -----------------------------------------------------"}
      <br />
      {"CREATE TABLE IF NOT EXISTS `mydb`.`Player` ("}
      <br />
      {"  `idPlayer` INT NOT NULL,"}
      <br />
      {"  `Name` VARCHAR(45) NULL,"}
      <br />
      {"  `FavoriteGame` INT NOT NULL,"}
      <br />
      {"  PRIMARY KEY (`idPlayer`, `FavoriteGame`),"}
      <br />
      {"  INDEX `fk_Player_Game1_idx` (`FavoriteGame` ASC),"}
      <br />
      {"  CONSTRAINT `fk_Player_Game1`"}
      <br />
      {"    FOREIGN KEY (`FavoriteGame`)"}
      <br />
      {"    REFERENCES `mydb`.`Game` (`idGame`)"}
      <br />
      {"    ON DELETE NO ACTION"}
      <br />
      {"    ON UPDATE NO ACTION)"}
      <br />
      {"ENGINE = InnoDB;"}
      <br /> <br />
      {"SET SQL_MODE=@OLD_SQL_MODE;"}
      <br />
      {"SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;"}
      <br />
      {"SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;"}
      <br />
    </text>
  </div>
);

export default SQL1;
